// <auto-generated />
namespace nmct.ba.cashlessproject.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class org : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(org));
        
        string IMigrationMetadata.Id
        {
            get { return "201501021448404_org"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
